github: JessicaTegner
custom:
  - https://thanks.dev/JessicaTegner
  - https://polar.sh/JessicaTegner
  - https://tidelift.com/subscription/pkg/pypi-pypandoc
  - https://tidelift.com/subscription/pkg/pypi-pypandoc-binary
